export const seedProjects = [
  {
    id: 'ai-podcast-generator',
    title: '基于多 Agent 协作的长文本播客自动化生产系统',
    subtitle: 'AI Podcast Generator',
    description: '面向知识内容音频化场景，构建从 PDF 解析到 TTS 合成的端到端自动化生产链路。',
    longDescription: '设计并实现长文本播客自动化生产系统，将 PDF 书籍转化为双人对话播客，覆盖 PDF 解析、内容结构化、脚本生成、口语润色、安全质检与 TTS 合成全链路。项目通过评论分析师、章节内容矿工、编剧、导演、审核员等 Agent 分阶段协作，提高长文本生成稳定性。',
    coverImage: '/projects/ai-podcast-generator.png',
    images: ['/projects/ai-podcast-generator.png'],
    techStack: ['React', 'Node.js', 'LLM', 'TTS', 'Multi-Agent'],
    tags: ['AI Coding', 'Agent', '内容生产'],
    githubUrl: '',
    demoUrl: '',
    status: 'published',
    priority: 10,
    featured: true,
    createdAt: '2025-05-01',
    updatedAt: '2026-05-24',
    rating: 5,
  },
  {
    id: 'market-survey-analytics',
    title: '烟雾报警器市场调查与分析',
    subtitle: 'Market Survey Analytics',
    description: '结合线上评论挖掘与线下问卷建模，形成烟雾报警器产品研发和推广策略。',
    longDescription: '项目从线上评论角度使用 Python 爬取 8067 条商品评论，并通过 ROST-CM 完成情感分析、语义网络分析等消费者特征挖掘。从线下问卷角度使用 SPSS 对 1080 份问卷进行 Logistic 回归和 K-means 聚类，最终输出产品研发与推广建议。该项目获“正大杯”全国大学生市场调查与分析大赛国家级三等奖。',
    coverImage: '/projects/market-survey-analytics.png',
    images: ['/projects/market-survey-analytics.png'],
    techStack: ['Python', 'SPSS', 'ROST-CM', 'Logistic Regression', 'K-means'],
    tags: ['数据分析', '市场调研', '建模'],
    githubUrl: '',
    demoUrl: '',
    status: 'published',
    priority: 8,
    featured: true,
    createdAt: '2023-04-01',
    updatedAt: '2026-05-24',
    rating: 4,
  },
  {
    id: 'pricing-optimization',
    title: '商超蔬菜定价供货策略',
    subtitle: 'Vegetable Pricing Optimization',
    description: '基于销售规律分析、时间序列预测和非线性规划，构建动态定价补货策略。',
    longDescription: '项目针对蔬菜品类和单品进行季节性销售分析与关联性分析，使用 ARIMA 模型预测未来七天销量，并通过 BP 神经网络建立销量到售价的非线性预测。最终结合品类组合、退货率、最小订购量等约束构建非线性规划模型，实现七日定价补货策略优化。该项目获全国大学生数学建模竞赛省级特等奖。',
    coverImage: '/projects/pricing-optimization.png',
    images: ['/projects/pricing-optimization.png'],
    techStack: ['SPSS', 'ARIMA', 'BP Neural Network', 'Nonlinear Programming'],
    tags: ['数学建模', '预测', '优化'],
    githubUrl: '',
    demoUrl: '',
    status: 'published',
    priority: 9,
    featured: true,
    createdAt: '2023-11-01',
    updatedAt: '2026-05-24',
    rating: 5,
  },
  {
    id: 'ai-coding-archive',
    title: 'Yz AI Coding Growth Archive',
    subtitle: 'Personal AI Coding Portfolio',
    description: '用于记录 AI 编程、数据分析和自动化 Agent 成长轨迹的个人项目展示网站。',
    longDescription: '项目将个人简历、AI Coding 项目卡片、项目详情轮播、评分记录和成长时间线整合为可公开访问的网站。当前架构已升级为 Express + SQLite + uploads，可在腾讯云轻量应用服务器上持久化保存内容。',
    coverImage: '/projects/ai-coding-archive.png',
    images: ['/projects/ai-coding-archive.png'],
    techStack: ['React', 'Vite', 'Express', 'SQLite'],
    tags: ['Portfolio', 'Frontend', 'Full Stack'],
    githubUrl: 'https://github.com/yuanze7314/ai-coding-journal',
    demoUrl: '',
    status: 'published',
    priority: 7,
    featured: true,
    createdAt: '2026-05-20',
    updatedAt: '2026-05-24',
    rating: 4,
  },
]

export const seedTimeline = [
  {
    id: 'timeline-current',
    phase: 'Current',
    title: '整理项目复盘与求职材料',
    description: '系统梳理经管知识背景与 AI 技能库，沉淀可复用的策略、数据分析方法和代码片段。',
    order: 40,
    isCurrent: true,
    createdAt: '2026-05-24',
    updatedAt: '2026-05-24',
  },
  {
    id: 'timeline-phase-3',
    phase: 'Phase 3',
    title: '开始搭建 AI Coding 项目展示网站',
    description: '设计并部署专属个人成长档案，将项目截图、说明、评分和简历信息整合到同一展示系统。',
    order: 30,
    isCurrent: false,
    createdAt: '2026-05-20',
    updatedAt: '2026-05-20',
  },
  {
    id: 'timeline-phase-2',
    phase: 'Phase 2',
    title: '开发 A股热点日报 Agent',
    description: '结合大模型 API 与自动化工作流，实现金融信息的数据清洗、热点提炼与策略输出。',
    order: 20,
    isCurrent: false,
    createdAt: '2026-05-12',
    updatedAt: '2026-05-12',
  },
  {
    id: 'timeline-phase-1',
    phase: 'Phase 1',
    title: '完善 AI 产品实习作品集',
    description: '探索大模型在内容生产、行业分析和学术研究中的实际落地场景。',
    order: 10,
    isCurrent: false,
    createdAt: '2026-05-01',
    updatedAt: '2026-05-01',
  },
]

export const seedDossier = {
  name: '袁 泽',
  status: ['立刻到岗', '出勤五天', '六个月以上'],
  phone: '18732865855',
  email: 'yzz7314@163.com',
  education: [
    { school: '中国海洋大学', major: '区域经济学', period: '2025.09 - 2028.06', active: true },
    { school: '中国石油大学（北京）', major: '经济学', period: '2021.09 - 2025.06', active: false },
  ],
  highlights: [
    '快手主站 - 热点运营中心策略产品经理：负责热词挖掘策略与热点 push 看板。',
    'AI 系统搭建：搭建多 Agent 长文本播客自动化生产系统，覆盖 PDF 解析、脚本生成、质检与 TTS 合成。',
    '数据分析建模：完成评论数据分析、问卷建模、动态定价补货等数据分析与建模项目。',
  ],
  awards: [
    { title: '美国大学生数学建模竞赛', level: '国家级一等奖' },
    { title: '“正大杯”全国大学生市场调查与分析大赛', level: '国家级三等奖' },
    { title: '中国国际大学生创新大赛（2024）', level: '国家级三等奖' },
    { title: '全国大学生数学建模竞赛', level: '省级特等奖' },
  ],
  skills: [
    { label: 'Data Analytics', value: '熟悉 Python、SQL，能够完成数据清洗、建模分析与结果解读。' },
    { label: 'AI Application', value: '持续使用 ChatGPT、Gemini、DeepSeek 等工具提升信息处理和方案产出效率。' },
    { label: 'AI Coding', value: '熟悉 Claude Code、Codex、Cursor、Trae、Coze，具备将想法快速落地为原型的能力。' },
  ],
}
